version: '3'
services:
  experiment-database:
    image: postgres:10-alpine
    # image: postgres:11-alpine
    volumes:
      - ./schemas/_functions.sql:/docker-entrypoint-initdb.d/functions.sql
      - ./schemas/simple-layers.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_DB=experiment_db
      - POSTGRES_USER=experiment_user
      - POSTGRES_PASSWORD=asdf
    ports:
      - "5432:5432"
    command: postgres -c 'max_wal_size=2GB'
