version: '3'
services:
  experiment-database:
    image: postgres:10-alpine
    volumes:
      - ./old.sql:/docker-entrypoint-initdb.d/old.sql
    environment:
      - POSTGRES_DB=experiment_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=asdf
    ports:
      - "5432:5432"
    command: postgres -c 'max_wal_size=2GB'
